CREATE TABLE categorias (id INTEGER UNIQUE PRIMARY KEY, nombre VARCHAR(100) DEFAULT '', seleccion BOOLEAN DEFAULT 0, activa BOOLEAN DEFAULT 0)
CREATE TABLE fuentes (id INTEGER UNIQUE PRIMARY KEY, nombre VARCHAR(100) DEFAULT '', op_fe BOOLEAN DEFAULT 0, op_and BOOLEAN DEFAULT 0, op_or BOOLEAN DEFAULT 0, id_categoria INTEGER DEFAULT 0, seleccion BOOLEAN DEFAULT 0, activa BOOLEAN DEFAULT 0)
CREATE TABLE busquedas (id INTEGER UNIQUE PRIMARY KEY, texto VARCHAR(100) DEFAULT '', op_fe BOOLEAN DEFAULT 0, op_and BOOLEAN DEFAULT 0, op_or BOOLEAN DEFAULT 0, id_categoria INTEGER DEFAULT 0, num_resultados INTEGER DEFAULT 0, fecha DATE DEFAULT '', id_carpeta INTEGER DEFAULT 0, fuentes VARCHAR(255))
CREATE TABLE resultados (id INTEGER UNIQUE PRIMARY KEY, titulo VARCHAR(255) DEFAULT '', texto VARCHAR(255) DEFAULT '', enlace VARCHAR(255) DEFAULT '', id_fuente INTEGER DEFAULT 0, idioma VARCHAR(2) DEFAULT '', id_busqueda INTEGER DEFAULT 0, icono INTEGER DEFAULT 0, checksum VARCHAR(32) DEFAULT '', fecha DATE DEFAULT '', nota VARCHAR(255) DEFAULT '')
CREATE TABLE carpetas (id INTEGER UNIQUE PRIMARY KEY, nombre VARCHAR(50) DEFAULT '', pertenece INTEGER DEFAULT 0, abierta BOOLEAN DEFAULT 0)
CREATE TABLE configuracion (id_cliente VARCHAR(50) DEFAULT '', servidor VARCHAR(255) DEFAULT '')

INSERT INTO carpetas (nombre, abierta, pertenece) VALUES ('Mis búsquedas', 1, 0)
INSERT INTO configuracion (id_cliente, servidor) VALUES ('', '')
